name: azure-deploy

on:
  push:
    branches: [ master ]

env:
  AZURE_RESOURCE_GROUP_NAME: 'ByTheMeterGroup'
  AZURE_FUNCTIONAPP_NAME: 'bythemeterapp'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}/src/ByTheMeter'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/build-artifacts'
  BUILD_PACKAGE_NAME: 'az-func.zip'

defaults:
  run:
    shell: bash

jobs:
  deploy-az-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Checking out source code ...'
        uses: actions/checkout@v2

      - name: 'Creating Azure Function App'
        uses: azure/CLI@v1
        with:
        inlineScript: |
          az deployment group create \
          --name az-func-workflow-deploy \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          --template-file $GITHUB_WORKSPACE/ArmTemplates/template.json \
          --mode incremental \
          --parameters $GITHUB_WORKSPACE/ArmTemplates/parameters.json


  build-az-function:
    needs: [deploy-az-infrastructure]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out source code...'
        uses: actions/checkout@v2

      - name: 'Package code'
        shell: bash
        run: |
          publishfolder="${{ github.workspace }}/output"
          mkdir $publishfolder
          cd $publishfolder
          cp ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/function.json .
          cp ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/index.js .
          mkdir ${{ env.BUILD_OUTPUT_PATH }}
          zip -r ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }} .

      - name: 'Package Azure function release build'
        uses: actions/upload-artifact@v2
        with:
        name: build_artifacts
        path: ${{ env.BUILD_OUTPUT_PATH }}
        if-no-files-found: error

  deploy-az-function:
    needs: [build-az-function]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out source code ...'
        uses: actions/checkout@v2

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

      - name: 'Fetching Azure Functions Publishing Profile'
        id: fncapp
        uses: azure/powershell@v1
        with:
        inlineScript: |
          $profile = ""
          $profile = Get-AzWebAppPublishingProfile -ResourceGroupName $env:AZURE_RESOURCE_GROUP_NAME -Name $env:AZURE_FUNCTIONAPP_NAME
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=pubprofile::$profile"
          Remove-Variable profile
        azPSVersion: "latest"

      - name: 'Create output directory'
        shell: bash
        run: |
          mkdir ${{ env.BUILD_OUTPUT_PATH }}

      - name: 'Download Azure function release build'
        uses: actions/download-artifact@v2
        with:
        name: build_artifacts
        path: ${{ env.BUILD_OUTPUT_PATH }}

      - name: 'Run Azure Functions Action'
        uses: azure/functions-action@v1
        with:
        app-name: ${{ env.FUNCTIONAPP_NAME }}
        package: ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }}
        publish-profile: ${{ steps.fncapp.outputs.pubprofile }}
        

